# Generated by Django 3.2.7 on 2021-10-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=40, null=True, verbose_name='date')),
                ('weather', models.CharField(blank=True, max_length=20, null=True, verbose_name='weather')),
                ('temp_min', models.FloatField(blank=True, null=True, verbose_name='temp_min')),
                ('temp_max', models.FloatField(blank=True, null=True, verbose_name='temp_max')),
                ('feels_like_day', models.FloatField(blank=True, null=True, verbose_name='feels_like_day')),
                ('pressure', models.IntegerField(blank=True, null=True, verbose_name='pressure')),
                ('humidity', models.IntegerField(blank=True, null=True, verbose_name='humidity')),
                ('dew_point', models.FloatField(blank=True, null=True, verbose_name='dew_point')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='wind_speed')),
                ('uvi', models.FloatField(blank=True, null=True, verbose_name='uvi')),
                ('pop', models.IntegerField(blank=True, null=True, verbose_name='pop')),
            ],
            options={
                'verbose_name': 'GoodDay',
                'verbose_name_plural': 'GoodDays',
                'ordering': ['-date'],
            },
        ),
    ]
