# Generated by Django 3.2.7 on 2021-09-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prop1', models.CharField(max_length=20, verbose_name='prop1')),
                ('prop2', models.CharField(blank=True, max_length=20, null=True, verbose_name='prop2')),
                ('prop3', models.CharField(blank=True, max_length=20, null=True, verbose_name='prop3')),
            ],
            options={
                'verbose_name': 'GoodDay',
                'verbose_name_plural': 'GoodDays',
                'ordering': ['-prop1'],
            },
        ),
    ]
