# Generated by Django 3.2.7 on 2021-10-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoodDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(verbose_name='temp')),
                ('temp_feels_like', models.FloatField(blank=True, null=True, verbose_name='temp_feels_like')),
                ('humidity', models.IntegerField(blank=True, null=True, verbose_name='humidity')),
                ('pressure', models.IntegerField(blank=True, null=True, verbose_name='pressure')),
                ('wind_speed', models.FloatField(blank=True, null=True, verbose_name='wind_speed')),
                ('weather', models.CharField(blank=True, max_length=20, null=True, verbose_name='weather')),
                ('date', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'GoodDay',
                'verbose_name_plural': 'GoodDays',
                'ordering': ['-temp'],
            },
        ),
    ]
