# Generated by Django 3.2.7 on 2021-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodweather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodday',
            options={'ordering': ['-date'], 'verbose_name': 'GoodDay', 'verbose_name_plural': 'GoodDays'},
        ),
        migrations.RemoveField(
            model_name='goodday',
            name='temp',
        ),
        migrations.RemoveField(
            model_name='goodday',
            name='temp_feels_like',
        ),
        migrations.AddField(
            model_name='goodday',
            name='dew_point',
            field=models.FloatField(blank=True, null=True, verbose_name='dew_point'),
        ),
        migrations.AddField(
            model_name='goodday',
            name='feels_like_day',
            field=models.FloatField(blank=True, null=True, verbose_name='feels_like_day'),
        ),
        migrations.AddField(
            model_name='goodday',
            name='pop',
            field=models.IntegerField(blank=True, null=True, verbose_name='pop'),
        ),
        migrations.AddField(
            model_name='goodday',
            name='temp_max',
            field=models.FloatField(blank=True, null=True, verbose_name='temp_max'),
        ),
        migrations.AddField(
            model_name='goodday',
            name='temp_min',
            field=models.FloatField(blank=True, null=True, verbose_name='temp_min'),
        ),
        migrations.AddField(
            model_name='goodday',
            name='uvi',
            field=models.FloatField(blank=True, null=True, verbose_name='uvi'),
        ),
        migrations.AlterField(
            model_name='goodday',
            name='date',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='date'),
        ),
    ]
